on: ['push', 'pull_request']

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verificando o repositório do Github
          uses: actions/checkout@v2

        - name: Instalando o node com a versão 14
          uses: actions/setup-node@v1
          with:
            node-version: 14

        - name: instalando as dependências de package.json
          run: npm install

        - name: executando o lint para verificação de erros
          run: npx eslint .
          